### ISSUE TITLE
Age adjustments

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-characters#18]
- Track _minimum_ age from career selection
- Add age data to Race CSV
- Use minimum age + race to determine if young/old categories can fit

**Comment by jsomara** [comment]
@morrus I added adult_range to the races CSV, but it's missing from a few of them that weren't in the PRD

**Comment by Morrus** [comment]
Weren't in the what?

I can add em when I next get some time. Don't worry about them.

**Comment by jsomara** [comment]
Err, whatever you call the online resource :)

**Comment by jsomara** [comment]
Didnt see them in the rulebook etiher, but just feel free to add them any time. Not blocking anything.

**Comment by Morrus** [comment]
(Forget to mention -  I added 'em yesterday.)

**Comment by jsomara** [comment]
I believe this is closed, and the remaining issue - the age range + dice roll - is tracked by #9
