### ISSUE TITLE
Add Race size bonus to DEFENSE

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-characters#25]
Borian, for example, is Small and gives +4 to DEFENSE

**Comment by jsomara** [comment]
@Morrus is the racial bonus applied before or after you take the floor of [defense score, 10]? Ie, if my defense score works out to 7 before calculating my race bonus, should my final score be 11 or 14

**Comment by Morrus** [comment]
The minimum is applied right at the end if the final score is below 10.

**Comment by jsomara** [comment]
Wonderful,that is how I just implemented it - closing
