### ISSUE TITLE
Vertical jump not calculated correctly

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-characters#27]
![screenshot 2016-07-26 14 01 05](https://cloud.githubusercontent.com/assets/29121/17201377/b018ffae-5442-11e6-8186-a1860210f498.png)

**Comment by jsomara** [comment]
@Morrus can you tell what the correct vertical jump for this character should be?

**Comment by Morrus** [comment]
=STR score, but cannot exceed horizontal jump.
